[env]
PROJECT_NAME = "{{ config_root | basename }}"
_.python.venv = { path = ".venv", create = true }

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[settings.python]
uv_venv_auto = true

[tools]
python = "{{ get_env(name='PYTHON_VERSION', default='3') }}"
uv = "latest"

[tools."http:trunk"]
version = "latest"
url = "https://trunk.io/releases/trunk"

[tasks.bootstrap]
alias = "b"
description = "Install dependencies & bootstrap the project"
run = "uv sync"

[tasks.run]
description = "Run the application"
run = "uv run app.py"

[tasks.test]
alias = "t"
description = "Run tests"
run = "uv run pytest --verbose ."

[tasks.format]
alias = "fmt"
description = "Lint the code"
run = "trunk fmt"

[tasks.lint]
alias = "l"
description = "Lint and analyze the code"
run = "trunk check"

[tasks.ci]
description = "Run CI tasks"
depends = ["test", "lint", "format"]

[tasks.info]
description = "Print project information"
run = '''
echo "Project: $PROJECT_NAME"
echo "Virtual Environment: $VIRTUAL_ENV"
'''
